version: "3.4"
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    build:
      context: ../packages/back
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ../packages/back:/server
      - back_modules:/server/node_modules
    environment:
      - NODE_ENV=development
    ports:
    - "3000:3000"
    # depends_on:
    #   - db
    working_dir: /server
    command: "yarn start:dev"
    
volumes:
  postgres:
  back_modules: